#
# Makefile for misc devices that really don't fit anywhere else.
#
obj- := misc.o	# Dummy rule to force built-in.o to be made

obj-$(CONFIG_IBM_ASM)	+= ibmasm/
obj-$(CONFIG_HDPU_FEATURES)	+= hdpuftrs/
obj-$(CONFIG_EEPROM_93CX6)    += eeprom_93cx6.o
obj-$(CONFIG_HP_ILO)		+= hpilo.o
obj-$(CONFIG_ENCLOSURE_SERVICES) += enclosure.o
