#
# Makefile for the eHEA ethernet device driver for IBM eServer System p
#
ehea-objs = ehea_main.o ehea_phyp.o ehea_qmr.o ehea_ethtool.o ehea_phyp.o
obj-$(CONFIG_EHEA) += ehea.o
CFLAGS += -DTARGET_BACKLVEL
